### ISSUE TITLE
Does not save to database

### ISSUE THREAD

**Issue by marvinfisher9** [xdavidhu/probeSniffer#3] opened 2017-04-27 14:33 UTC
```
[I] Stopping...
[I] Results saved to 'DB-probeSniffer.db'

[I] probeSniffer stopped.
```
DB-probeSniffer.db was created, but there are no entries. Although in the terminal they are displayed

**Comment by xdavidhu** [comment] 2017-05-01 10:41
Hey!

Make sure you are running in the latest version of Pyton.
Also use SQLite3 to query the databse file.

**Comment by marvinfisher9** [comment] 2017-05-02 07:26
I use : 
python3 probeSniffer.py wlan1mon

and: 
sqlite3

But error still remains. More precisely, there is no error. The database is created, the header is correct, but the data itself is not written to it. And the size is always 12.3 Kb. And I always get it at the end:

[I] Stopping...
[I] Results saved to 'DB-probeSniffer.db'

[I] probeSniffer stopped.

**Comment by xdavidhu** [comment] 2017-05-17 21:49
Is the issue still reproducable?

**Comment by marvinfisher9** [comment] 2017-05-19 12:23
Yes

**Comment by xdavidhu** [comment] 2017-10-09 16:06
Sorry, I'm closing the issue since I can't reproduce the problem.

If you are still having problems feel free to open a new issue.

**Closed as completed by xdavidhu** 2017-10-09 16:06 UTC
